# Generated by Django 4.1 on 2022-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=30)),
                ('Language', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Genre', models.CharField(max_length=15)),
                ('Sales', models.IntegerField()),
            ],
        ),
    ]
